kind: pipeline
name: default

clone:
  disable: false

steps:
- name: build
  image: node
  commands:
          - npm install
          - sls create --template aws-python3 --path serverless
          - ls -lrt
