kind: pipeline
name: default

clone:
  disable: false

steps:
- name: build
  image: node
  commands:
          - npm install --save-dev
          - node ./node_modules/serverless/bin/serverless create --template aws-python3 --path serverless
          - ls -lrt
